// Copyright lowRISC contributors.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// Register Top module auto-generated by `reggen`


`include "common_cells/assertions.svh"

module viterbi_reg_top #(
    parameter type reg_req_t = logic,
    parameter type reg_rsp_t = logic,
    parameter int AW = 5
) (
  input clk_i,
  input rst_ni,
  input  reg_req_t reg_req_i,
  output reg_rsp_t reg_rsp_o,
  // To HW
  output viterbi_reg_pkg::viterbi_reg2hw_t reg2hw, // Write
  input  viterbi_reg_pkg::viterbi_hw2reg_t hw2reg, // Read


  // Config
  input devmode_i // If 1, explicit error return for unmapped register access
);

  import viterbi_reg_pkg::* ;

  localparam int DW = 32;
  localparam int DBW = DW/8;                    // Byte Width

  // register signals
  logic           reg_we;
  logic           reg_re;
  logic [AW-1:0]  reg_addr;
  logic [DW-1:0]  reg_wdata;
  logic [DBW-1:0] reg_be;
  logic [DW-1:0]  reg_rdata;
  logic           reg_error;

  logic          addrmiss, wr_err;

  logic [DW-1:0] reg_rdata_next;

  // Below register interface can be changed
  reg_req_t  reg_intf_req;
  reg_rsp_t  reg_intf_rsp;


  assign reg_intf_req = reg_req_i;
  assign reg_rsp_o = reg_intf_rsp;


  assign reg_we = reg_intf_req.valid & reg_intf_req.write;
  assign reg_re = reg_intf_req.valid & ~reg_intf_req.write;
  assign reg_addr = reg_intf_req.addr;
  assign reg_wdata = reg_intf_req.wdata;
  assign reg_be = reg_intf_req.wstrb;
  assign reg_intf_rsp.rdata = reg_rdata;
  assign reg_intf_rsp.error = reg_error;
  assign reg_intf_rsp.ready = 1'b1;

  assign reg_rdata = reg_rdata_next ;
  assign reg_error = (devmode_i & addrmiss) | wr_err;


  // Define SW related signals
  // Format: <reg>_<field>_{wd|we|qs}
  //        or <reg>_{wd|we|qs} if field == 1 or 0
  logic [7:0] datax_wd;
  logic datax_we;
  logic [7:0] datay_wd;
  logic datay_we;
  logic [7:0] state_wd;
  logic state_we;
  logic [7:0] bitout_qs;
  logic bitout_re;
  logic ctrl1_wd;
  logic ctrl1_we;
  logic status_qs;
  logic status_re;

  // Register instances
  // R[datax]: V(False)

  prim_subreg #(
    .DW      (8),
    .SWACCESS("WO"),
    .RESVAL  (8'h0)
  ) u_datax (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (datax_we),
    .wd     (datax_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.datax.q ),

    .qs     ()
  );


  // R[datay]: V(False)

  prim_subreg #(
    .DW      (8),
    .SWACCESS("WO"),
    .RESVAL  (8'h0)
  ) u_datay (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (datay_we),
    .wd     (datay_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.datay.q ),

    .qs     ()
  );


  // R[state]: V(False)

  prim_subreg #(
    .DW      (8),
    .SWACCESS("WO"),
    .RESVAL  (8'h0)
  ) u_state (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (state_we),
    .wd     (state_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.state.q ),

    .qs     ()
  );


  // R[bitout]: V(True)

  prim_subreg_ext #(
    .DW    (8)
  ) u_bitout (
    .re     (bitout_re),
    .we     (1'b0),
    .wd     ('0),
    .d      (hw2reg.bitout.d),
    .qre    (),
    .qe     (),
    .q      (),
    .qs     (bitout_qs)
  );


  // R[ctrl1]: V(True)

  prim_subreg_ext #(
    .DW    (1)
  ) u_ctrl1 (
    .re     (1'b0),
    .we     (ctrl1_we),
    .wd     (ctrl1_wd),
    .d      ('0),
    .qre    (),
    .qe     (reg2hw.ctrl1.qe),
    .q      (reg2hw.ctrl1.q ),
    .qs     ()
  );


  // R[status]: V(True)

  prim_subreg_ext #(
    .DW    (1)
  ) u_status (
    .re     (status_re),
    .we     (1'b0),
    .wd     ('0),
    .d      (hw2reg.status.d),
    .qre    (),
    .qe     (),
    .q      (),
    .qs     (status_qs)
  );




  logic [5:0] addr_hit;
  always_comb begin
    addr_hit = '0;
    addr_hit[0] = (reg_addr == VITERBI_DATAX_OFFSET);
    addr_hit[1] = (reg_addr == VITERBI_DATAY_OFFSET);
    addr_hit[2] = (reg_addr == VITERBI_STATE_OFFSET);
    addr_hit[3] = (reg_addr == VITERBI_BITOUT_OFFSET);
    addr_hit[4] = (reg_addr == VITERBI_CTRL1_OFFSET);
    addr_hit[5] = (reg_addr == VITERBI_STATUS_OFFSET);
  end

  assign addrmiss = (reg_re || reg_we) ? ~|addr_hit : 1'b0 ;

  // Check sub-word write is permitted
  always_comb begin
    wr_err = (reg_we &
              ((addr_hit[0] & (|(VITERBI_PERMIT[0] & ~reg_be))) |
               (addr_hit[1] & (|(VITERBI_PERMIT[1] & ~reg_be))) |
               (addr_hit[2] & (|(VITERBI_PERMIT[2] & ~reg_be))) |
               (addr_hit[3] & (|(VITERBI_PERMIT[3] & ~reg_be))) |
               (addr_hit[4] & (|(VITERBI_PERMIT[4] & ~reg_be))) |
               (addr_hit[5] & (|(VITERBI_PERMIT[5] & ~reg_be)))));
  end

  assign datax_we = addr_hit[0] & reg_we & !reg_error;
  assign datax_wd = reg_wdata[7:0];

  assign datay_we = addr_hit[1] & reg_we & !reg_error;
  assign datay_wd = reg_wdata[7:0];

  assign state_we = addr_hit[2] & reg_we & !reg_error;
  assign state_wd = reg_wdata[7:0];

  assign bitout_re = addr_hit[3] & reg_re & !reg_error;

  assign ctrl1_we = addr_hit[4] & reg_we & !reg_error;
  assign ctrl1_wd = reg_wdata[0];

  assign status_re = addr_hit[5] & reg_re & !reg_error;

  // Read data return
  always_comb begin
    reg_rdata_next = '0;
    unique case (1'b1)
      addr_hit[0]: begin
        reg_rdata_next[7:0] = '0;
      end

      addr_hit[1]: begin
        reg_rdata_next[7:0] = '0;
      end

      addr_hit[2]: begin
        reg_rdata_next[7:0] = '0;
      end

      addr_hit[3]: begin
        reg_rdata_next[7:0] = bitout_qs;
      end

      addr_hit[4]: begin
        reg_rdata_next[0] = '0;
      end

      addr_hit[5]: begin
        reg_rdata_next[0] = status_qs;
      end

      default: begin
        reg_rdata_next = '1;
      end
    endcase
  end

  // Unused signal tieoff

  // wdata / byte enable are not always fully used
  // add a blanket unused statement to handle lint waivers
  logic unused_wdata;
  logic unused_be;
  assign unused_wdata = ^reg_wdata;
  assign unused_be = ^reg_be;

  // Assertions for Register Interface
  `ASSERT(en2addrHit, (reg_we || reg_re) |-> $onehot0(addr_hit))

endmodule
